### ISSUE TITLE
Clarification needed on k values for graph construction in evaluation metrics

### ISSUE THREAD

**Issue by newtonharry** [RoseYuan/sc_chromatin_benchmark#3]
Dear @RoseYuan ,

I've been studying your excellent benchmarking paper on computational methods for single-cell chromatin data analysis. I'm trying to implement some of the evaluation metrics you've used, but I'm confused about the specific k values used for graph construction in different metrics. Could you please clarify:

1. For the Proportion of Weakly Connected (PWC) metric:
   - What value of k was used?

2. For cLISI:
   - The paper mentions k=90. Is this for constructing a kNN graph, or is it just the neighborhood size for the metric calculation? I've found a python implementation of the metric and it uses k0=90. Is this what you mean? https://scib.readthedocs.io/en/latest/api/scib.metrics.clisi_graph.html

3. For ASW and FNS:
   - The paper mentions k>300, is this referring to the generation of the neighbourhood needed for the calculation? If so is it using a kNN or SNN? Does this mean I can choose any k above 300 here?

4. For other graph-based analyses:
   - Is k=20 (mentioned for Geary's C calculation) used consistently for all other graph constructions?

A clear understanding of these details would greatly help in accurately reproducing and extending your benchmarking framework. Thank you for your time and patience in answering these question where possible.

**Comment by RoseYuan** [comment]
Hi @newtonharry,

Thank you for your interest and your question.

1. For PWC I'm using k=20, which is the default k used in [Seurat]((https://satijalab.org/seurat/reference/findneighbors))'s `FindNeighbors()` for constructing a KNN(SNN) graph.
2. k=90 in cLISI is the k for the metric calculation.
3. For ASW and FNS, k>300 is just an estimation for us to discuss about the metric (because ASW and FNS is calculated per cluster, and in our datasets, most clusters are of a size > 300 cells). ASW and FNS do not require constructing a graph in their calculation, nor selecting a k.
4. For other graph-based analysis: yes, if not specified, I used k=20 by default.

I hope this answers your question. If not, please let me know.
